### ISSUE TITLE
"type object 'Rotation' has no attribute 'from_matrix'"

### ISSUE THREAD

**Issue by rmcgibbo** [qzhu2017/PyXtal#131]
Hi!

I just downloaded PyXtal and started trying to get started. The first error I observed when trying to run an example from the documentation with this code:

```
from pyxtal import pyxtal
my_crystal = pyxtal(molecular=True)
my_crystal.from_random(3, 36, ['H2O'], [4])
```

```
Traceback (most recent call last):
  File "<ipython-input-8-f0a68669a2a8>", line 4, in <module>
    my_crystal.from_random(3, 36, ['H2O'], [4])
  File "/path/to/pyxtal-0.1.9/lib/python3.7/site-packages/pyxtal/__init__.py", line 247, in from_random
    lattice=lattice, sites=sites, conventional=conventional, diag=diag, tm=tm)
  File "/path/to/pyxtal-0.1.9/lib/python3.7/site-packages/pyxtal/molecular_crystal.py", line 91, in __init__
    tm,
  File "/path/to/pyxtal-0.1.9/lib/python3.7/site-packages/pyxtal/molecular_crystal.py", line 167, in init_common
    self.get_orientations()
  File "/path/to/pyxtal-0.1.9/lib/python3.7/site-packages/pyxtal/molecular_crystal.py", line 273, in get_orientations
    allow_inversion=self.allow_inversion,
  File "/path/to/pyxtal-0.1.9/lib/python3.7/site-packages/pyxtal/molecule.py", line 700, in orientation_in_wyckoff_position
    opa = OperationAnalyzer(op_m)
  File "/path/to/pyxtal-0.1.9/lib/python3.7/site-packages/pyxtal/operations.py", line 792, in __init__
    rotvec = Rotation.from_matrix(self.m).as_rotvec()
AttributeError: type object 'Rotation' has no attribute 'from_matrix'
```

Any help would be greatly appreciated. I'm probably just doing something wrong.

**Comment by rmcgibbo** [comment]
Ah. I think this means I'm using too old of a scipy.
