### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by aglie** [qzhu2017/PyXtal#135]
Could you help me, I have trouble installing pyxtal. 

I start from new virtual environment:

```
conda create -n pyxtal python=3
conda activate pyxtal
pip install pyxtal
python -c "import pyxtal"
```

and in the end having a problem importing the library:

```
(pyxtal) asimonov@matl ~ % python -c "import pyxtal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/asimonov/opt/anaconda3/envs/pyxtal/lib/python3.9/site-packages/pyxtal/__init__.py", line 16, in <module>
    from pyxtal.molecular_crystal import (
  File "/Users/asimonov/opt/anaconda3/envs/pyxtal/lib/python3.9/site-packages/pyxtal/molecular_crystal.py", line 15, in <module>
    from pyxtal.wyckoff_site import mol_site, WP_merge
  File "/Users/asimonov/opt/anaconda3/envs/pyxtal/lib/python3.9/site-packages/pyxtal/wyckoff_site.py", line 10, in <module>
    from pymatgen import Molecule
ImportError: cannot import name 'Molecule' from 'pymatgen' (unknown location)
```

To me this looks like an issue with the version of the libraries, since `pymatgen` now has `IMolecule` class instead of `Molecule`.

Could you tell me what should I do to install pyxtal properly?

**Comment by qzhu2017** [comment]
Recently, pymatgen made a major change.

To support the latest version of pymatgen, please use the pyxtal-v0.2.2 or higher
`pip install pyxtal==0.2.2`

**Comment by aglie** [comment]
Awesome, that works, thank you.

**Comment by jan-janssen** [comment]
To simplify the installation via `conda-forge` I created a `conda-forge` package: https://anaconda.org/conda-forge/pyxtal
