### ISSUE TITLE
VXRD: Comparison Error

### ISSUE THREAD

**Issue by sabaronett** [qzhu2017/PyXtal#148]
## Steps to reproduce
1. Run VXRD Flask web app locally following [instructions here](https://github.com/qzhu2017/PyXtal/tree/master/flask).
2. On the ***Comparison*** page, upload any valid .CIF or .POSCAR as your two (2) "Input Files" (e.g., test files in `PyXtal\flask\instance\uploads`), then hit the **Visualize** button.

## Flask error traceback
```bash
127.0.0.1 - - [08/Jun/2021 19:34:41] "GET /comparison HTTP/1.1" 200 -
127.0.0.1 - - [08/Jun/2021 19:34:58] "POST /comparison HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/stanley/miniconda3/envs/pyxtal2/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/stanley/github/qzhu2017/PyXtal/flask/app/routes.py", line 65, in comparison
    plot=compare())
  File "/home/stanley/github/qzhu2017/PyXtal/flask/app/routes.py", line 231, in compare
    S = Similarity(xrds[0].spectra,
AttributeError: 'XRD' object has no attribute 'spectra'
```

**Comment by qzhu2017** [comment]
@sabaronett 

I am trying to following the steps to reproduce the error, however, I got the following when I click the comparison page

```
~/Desktop/GitHub/PyXtal/flask$ flask run
 * Serving Flask app "vxrd.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 319-908-302
127.0.0.1 - - [11/Jun/2021 09:53:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:36] "GET /static/css/custom.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:36] "GET /static/img/brand.png HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:36] "GET /static/jsmol.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:36] "GET /static/img/logo.png HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:36] "GET /static/jsmol/JSmol.min.js HTTP/1.1" 404 -
127.0.0.1 - - [11/Jun/2021 09:53:37] "GET /static/img/grid.jpg HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:37] "GET /static/img/favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:40] "GET /comparison HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/qiangzhu/Desktop/GitHub/PyXtal/flask/app/routes.py", line 44, in comparison
    form = MainForm()
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super().__init__(formdata=formdata, **kwargs)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/wtforms/form.py", line 278, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/wtforms/form.py", line 132, in process
    field.process(formdata)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/wtforms/csrf/core.py", line 43, in process
    self.current_token = self.csrf_impl.generate_csrf_token(self)
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask_wtf/csrf.py", line 140, in generate_csrf_token
    return generate_csrf(
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask_wtf/csrf.py", line 34, in generate_csrf
    secret_key = _get_config(
  File "/Users/qiangzhu/anaconda3/lib/python3.8/site-packages/flask_wtf/csrf.py", line 129, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF.
127.0.0.1 - - [11/Jun/2021 09:53:40] "GET /comparison?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:40] "GET /comparison?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:40] "GET /comparison?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:40] "GET /comparison?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:40] "GET /comparison?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2021 09:53:40] "GET /comparison?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
^C^C

```

**Comment by sabaronett** [comment]
@qzhu2017

Not sure if you ran `pip install -r requirements.txt` in `PyXtal/flask/` beforehand, but I made recent changes to that file that may resolve some of those issues. Let me know if not.

**Comment by qzhu2017** [comment]
Yes, I did run `pip install -r requirements.txt`

**Comment by sabaronett** [comment]
@qzhu2017, add this to your `.bashrc` (or equivalent) and try again:
```bash
# VXRD Flask Environment Variables
export SECRET_KEY=asdf1234
```
(see [`flask/config.py`](https://github.com/qzhu2017/PyXtal/blob/master/flask/config.py)). You can change `asdf1234` to whatever you want.

**Comment by qzhu2017** [comment]
@sabaronett 
I made a fix and it works now. However, I am not happy with the figure size. Do you know how to reduce the height of the plot?

<img width="517" alt="image" src="https://user-images.githubusercontent.com/29445366/121795115-6e539f00-cbc2-11eb-918e-a7c93030bb12.png">

**Comment by sabaronett** [comment]
@qzhu2017, I set the plot height to 450px:
https://github.com/qzhu2017/PyXtal/blob/41a0d7aa66f4d37c1698af59c367b768508a55de/flask/app/routes.py#L253-L254
Feel free to adjust as desired and close this issue.
