### ISSUE TITLE
[Bug]Cannot generate molecules on the special site due to recent changes.

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#158]
```python
from pyxtal import pyxtal

s = pyxtal(molecular=True)
s.from_random(3, 61, ["Benzene"], [4])
print(s)
```
```
(base) qiangzhu@deptanonpool-238 PyXtal (master) $ python 0.py 
/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/msg.py:21: UserWarning: Cannot generate crystal after max attempts.
  warn(text)
Traceback (most recent call last):
  File "0.py", line 4, in <module>
    s.from_random(3, 61, ["Benzene"], [4])
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/__init__.py", line 272, in from_random
    raise RuntimeError("long time to generate structure, check inputs")
RuntimeError: long time to generate structure, check inputs
```

**Comment by qzhu2017** [comment]
```python
>>> from pyxtal.symmetry import Group
>>> g1 = Group(27, 0)
>>> g1[0]
/Users/qiangzhu/anaconda3/lib/python3.7/site-packages/pymatgen/core/operations.py:411: UserWarning: Rotation matrix should be integer
  warnings.warn("Rotation matrix should be integer")
Wyckoff position 24g in Point group D6h with site symmetry 1
x, y, z
x, -y, -z
x, y, -z
-x/2-489061y/564719, 489061x/564719-y/2, z
x/2+489061y/564719, 489061x/564719-y/2, -z
x/2-489061y/564719, 489061x/564719+y/2, -z
x/2-489061y/564719, -489061x/564719-y/2, -z
x/2-489061y/564719, 489061x/564719+y/2, z
x, -y, z
-x, -y, z
-x/2+489061y/564719, 489061x/564719+y/2, -z
-x/2-489061y/564719, 489061x/564719-y/2, -z
x/2+489061y/564719, 489061x/564719-y/2, z
-x/2-489061y/564719, -489061x/564719+y/2, -z
x/2+489061y/564719, -489061x/564719+y/2, z
x/2-489061y/564719, -489061x/564719-y/2, z
-x/2+489061y/564719, -489061x/564719-y/2, z
-x, y, -z
-x, -y, -z
-x/2+489061y/564719, 489061x/564719+y/2, z
-x/2-489061y/564719, -489061x/564719+y/2, z
x/2+489061y/564719, -489061x/564719+y/2, -z
-x/2+489061y/564719, -489061x/564719-y/2, -z
-x, y, z

```
