### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#39]
@scottfredericks 
try to execute the following code. It looks like there is a bug when the input molecule has C1 symmetry.
```python
from pyxtal.molecular_crystal import molecular_crystal
from random import randint
from time import time 
from pymatgen.io.cif import CifWriter
import os

mols = ['CH4', 'H2O', 'NH3', 'benzene', 'C60', 'pentacene', 'roy', 'aspirin']
filename = 'out.cif'
if os.path.isfile(filename):
    os.remove(filename)

for mol in mols:
    for i in range(10):
        run = True
        while run:
            sg = 19 #randint(4, 191)
            start = time()
            rand_crystal = molecular_crystal(sg, [mol], [4], 2.0)
            if rand_crystal.valid:
                run = False
                print('SG: {0:d} Time: {1:.3f} seconds'.format(sg, time()-start))
                content = str(CifWriter(rand_crystal.struct, symprec=0.1))
                with open(filename, 'a+') as f:
                    f.writelines(content)

```
```
SG: 19 Time: 0.768 seconds
SG: 19 Time: 0.445 seconds
Traceback (most recent call last):
  File "1.py", line 18, in <module>
    rand_crystal = molecular_crystal(sg, [mol], [4], 2.0)
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/molecular_crystal.py", line 772, in __init__
    self.get_orientations()
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/molecular_crystal.py", line 813, in get_orientations
    allowed = orientation_in_wyckoff_position(mol, self.wyckoffs, self.w_symm, wp_index, already_oriented=True, allow_inversion=self.allow_inversion)
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/molecule.py", line 314, in orientation_in_wyckoff_position
    for op in gen_pos:
NameError: name 'gen_pos' is not defined
```

**Comment by scottfredericks** [comment]
@qzhu2017 
I have fixed the gen_pos issue. Also, I have increased the distance tolerance for molecular crystals to 2.4 times that used for atomic crystals. For printing the tolerances, I have moved this into a new issue "tolerance matrix class".
