### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#48]
@scottfredericks 
A bug after your recent commits
```
qiangzhu@Qiangs-MacBook-Pro:~/Desktop/github/PyXtal$ python pyxtal/test_cases/test_3D_molecule.py 
Mol:CH4         SG: 51 Time:0.69 seconds, N_attempts:   2 Vol: 216.51
Traceback (most recent call last):
  File "pyxtal/test_cases/test_3D_molecule.py", line 18, in <module>
    rand_crystal = molecular_crystal(sg, [mol], [4], 1.0)
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/molecular_crystal.py", line 1013, in __init__
    self.init_common(molecules, numMols, volume_factor, allow_inversion, orientations, check_atomic_distances, group, lattice, tm)
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/molecular_crystal.py", line 1001, in init_common
    self.generate_crystal()
  File "/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/molecular_crystal.py", line 1178, in generate_crystal
    self.struct = Msg1
NameError: name 'Msg1' is not defined
```

**Comment by scottfredericks** [comment]
@qzhu2017 
It should be fixed now.
